# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

commands:
  destroy_infrastructure:
    steps:
      - run:
          name: Destroy infrastructure
          command: |
            aws cloudformation delete-stack --stack-name cicd-basics
          when: on_fail

# Declare jobs
jobs:
  create_infrastructure:
    docker:
        - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          command: |
            aws cloudformation deploy \
              --template-body infra-template.yml \
              --stack-name cicd-basics
  configure_infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["95:cc:4a:2a:56:ac:93:91:3c:49:09:0d:83:d1:8e:b5"]
      - run:
          name: Install dependencies
          command: |
            apk add --update ansible # install the dependencies needed for your playbook
      - run:
          name: Configure server
          command: |
            ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i inventory playbook.yml
  smoke_test:
    docker:
        - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Simulate error
          command: |
            sleep 60
            return 1
      - destroy_infrastructure
      # - run:
      #     name: Destroy infrastructure
      #     command: |
      #       aws cloudformation delete-stack --stack-name cicd-basics
      #     when: on_fail

workflows:
  infra:
    jobs:
      - create_infrastructure
      - smoke_test